apiVersion: v1
kind: Service
metadata:
  name: lb-test
spec:
  selector:
    pod: lb-test-pod
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-test
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: lb-test-pod
  template:
    metadata:
      labels:
        pod: lb-test-pod
    spec:
      containers:
        - name: lb-test-container
          image: docker.io/leandersteiner/lb-test:latest
